[[conclusions]]
== Conclusions

The code sprint provided a significant opportunity to highlight the heterogeneous nature of metadata standards and perspectives from multiple stakeholders.  As a result it was possible to articulate a coherent framework for understanding scope of different activities and a propose a coherent architecture to guide ongoing work in metadata standards.

In addition, progress was made on a number of specific activities, providing a validation that the proposed framework can be progressed incrementally, without it being necessary for all participants to fully engage with all the diverse aspects of metadata standardisation. The general principles of improving FAIR-ness of metadata standards, whilst supporting multiple existing and emerging communities

=== Future Work

The sprint participants made the following recommendations regarding future work:

* Focus on FAIR publication of mappings between metadata standards
* Support for XSLT2 transformations in metadata publishing

Ongoing activities are planned as part of research projects to complete the implementation of the XAI approach using GeoDCAT, OGC API Processes and OGC API Records etc/


